### ISSUE TITLE
Using webpack5, dependencies get wiped out by addFilesToWebpackDeps()

### ISSUE THREAD

**Issue by DaveMBush** [UX-and-I/storybook-design-token#101]
As the title says. If you use webpack5 to build your code, the function [addFilestoWebpackDeps()](https://github.com/UX-and-I/storybook-design-token/blob/master/addon/src/plugin.ts#L22)  will wipe out everything except what gets passed via the files parameter.

I discovered this by using this plugin under Angular.  Adding this plugin makes it so that none of the changes I make to my TS files show up using HMR. But, I can make changes to CSS or HTML templates.

If you change the function to

``` typescript
function addFilesToWebpackDeps(compilation: any, files: string[]) {
  if(Array.isArray(compilation.fileDependencies)) {
    // If webpack4, fileDependencies will be an array
    compilation.fileDependencies = [...compilation.fileDependencies, ...files];
  } else {
    // In webpack5, fileDependencies is a LazySet.
    compilation.fileDependencies.addAll(files);
  }
}
```

Everything works as it should.

**Comment by JanSvejda** [comment]
I can confirm the above. Took me ages to find out what was causing the failing hot reload in storybook.

**Comment by Sqrrl** [comment]
Thank you for your PR @DaveMBush. Merged and published with v.2.2.0.
