### ISSUE TITLE
SVG icons are being found outside the project

### ISSUE THREAD

**Issue by RichardNorton** [UX-and-I/storybook-design-token#104]
storybook v14.1.4
storybook-design-token v2.1.0

We have our storybook project in a directory with a sub-directory (assets) that contain our SVGs, but the scan finds SVGs in folders outside our project folder.

Can we restrict where the scan looks?

**Comment by Sqrrl** [comment]
You can specify a custom glob pattern. See https://github.com/UX-and-I/storybook-design-token#specify-a-custom-glob-for-your-token-files

**Comment by RichardNorton** [comment]
Perfect
