### ISSUE TITLE
Bad layout of the TokenTable component in Safari

### ISSUE THREAD

**Issue by ilyamore88** [UX-and-I/storybook-design-token#120]
Position: relative doesn't work with tbody in Safari.

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/37909603/182004417-077eaf94-c172-4f2c-8773-94837db8243b.png">

Safari: Version 15.6 (16613.3.9.1.7, 16613)

**Comment by Sqrrl** [comment]
Thanks for reporting. Could you check v2.7.0. Should be fixed.

**Comment by ilyamore88** [comment]
Hi, @Sqrrl. It works fine, thank you!

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/37909603/196040611-2c8c505e-5caa-4449-84cf-468401779b53.png">
