### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by krisdigital** [UX-and-I/storybook-design-token#123]
Hello 👋,

we tried updating a project to React 18 but the dependencies for Storybook Design Token still say 16 or 17 - could this maybe be bumped up to 18, or are there more steps involved?

Thx!

**Comment by krisdigital** [comment]
@Sqrrl Thx for removing the dependency! it may take some time but I will let you know if it works with React 18 when I know more 😎

**Comment by Sqrrl** [comment]
I'm closing this for now. Please re-open if necessary.
