### ISSUE TITLE
Table variant of `DesignTokenDocBlock` not rendering in Firefox

### ISSUE THREAD

**Issue by julrich** [UX-and-I/storybook-design-token#129]
Not entirely sure when this broke, but something seems to have degraded / destroyed the `viewType="table"` version of `DesignTokenDocBlock` in Firefox (Linux for me). Reproducible with the official Storybook for me here (for example):
https://storybook-design-token-v1.netlify.app/?path=/story/design-tokens-typography--page

Looks like this on my system (and verified by at least one colleague on macOS Firefox):
![grafik](https://user-images.githubusercontent.com/136760/195316630-4e302c21-2db5-4169-8b84-c55abeb3bdbc.png)

The `viewType="card"` seems to be unaffected, but everything related to `table` ends in an endlessly scrollable, but empty, container.

**Comment by Sqrrl** [comment]
Thanks for reporting. Should be fixed with v2.8.0.

**Comment by julrich** [comment]
`2.8.0` fixes this for me! Feel free to close the issue if that's enough validation :)
