### ISSUE TITLE
Feature Request: Tokens as Story/Canvas

### ISSUE THREAD

**Issue by gossi** [UX-and-I/storybook-design-token#13]
Thanks for putting this addon together.

For now the tokens show up in the addons sidebar, which is a thing I'm wondering about. For me they are informative instead of letting you _customize_ the story at hand.

I would like to put them into the navigation of the sidebar and let them show up in the main/story area.

**Comment by Sqrrl** [comment]
Hey. This is already somewhat planned as part of the Storybook Docs Addon. See full discussion here: https://github.com/storybookjs/storybook/issues/7671

Therefore I would keep that out of the scope of this addon.

**Comment by gossi** [comment]
That is great to hear. I just released Theemo, read here about: https://gos.si/blog/say-hello-to-theemo-the-yordle-powered-theme-automator/

Basically the idea with this, is theemo already knows about all your tokens. Would like to connect theemo to this. In the end theemo automates everything for you, just one command left.

Let me know how to collaborate. Will also put a comment on storybook issue.

**Comment by 11joselu** [comment]
We have a Custom Component to generate dynamic Tokens with a MDX Story overview

_Note: This component only search for sass files._ 

```typescript
import React from 'react';
import { ScssParser } from 'storybook-design-token/dist/parsers/scss.parser.js';
import { TokenOverview } from 'storybook-design-token/dist/components/TokenOverview';
import { TokenFile } from 'storybook-design-token/dist/interfaces/token-files.interface';

type Props = {
  file: string;
};

const cache: Record<string, TokenFile[]> = {};
// Load all files because javascript could not read when is executing in browser
const scssReq = require.context(`!!raw-loader!./ui/`, true, /._*Tokens.scss$/);

const TokenGenerator: React.FunctionComponent<Props> = ({ file }: Props) => {
  let scssTokenFiles: TokenFile[] = cache[file];

  if (!scssTokenFiles) {
    scssTokenFiles = scssReq
      .keys()
      .filter((filename) => filename.includes(`${file}Tokens`))
      .map((filename) => ({ filename, content: scssReq(filename).default }));
    cache[file] = scssTokenFiles;
  }

  const scssParser = new ScssParser();
  const parsedScss = scssParser.parse({ scss: scssTokenFiles });

  return (
    <>
      {parsedScss.tokenGroups.map((token, index) => (
        <TokenOverview key={index} tokenGroup={token} viewType="table"></TokenOverview>
      ))}
    </>
  );
};

export default TokenGenerator;

```

Usage:

Alert.stories.mdx

```mdx
import { Meta, Story, Preview, Props } from '@storybook/addon-docs/blocks';
import Alert from './Alert';
import TokenGenerator from '../../TokenGenerator';

<Meta title="Alert" component={Alert} />

# Alerts


<Preview>
  <Story name="Information">
      <Alert>Hi this our brand new ui with a information</Alert>
  </Story>
</Preview>

<TokenGenerator file="Alert" />

```

This already solve our problem.

**Comment by codequistador** [comment]
Cool! I'm going to try this out.

**Comment by Sqrrl** [comment]
Hey.

It's been a while. Just wanted to let you know that v1 of the addon will come with custom doc blocks to add the token documentation to your stories/docs pages.

If you're still interested, you could check it out. Please the README below. The new version comes with new configuration instructions.

`yarn add storybook-design-token@next`

Readme is here: https://github.com/UX-and-I/storybook-design-token/tree/v1
