### ISSUE TITLE
Addon fails to load

### ISSUE THREAD

**Issue by spencerfrost** [UX-and-I/storybook-design-token#132]
I'm running Storybook 6.5.12 for Vue 2.6. and I'm unable to load this addon for some reason. 
I get the following output when I start Storybook. 
All I have done is simply add the addon to my `addons` in the `main.js` file.
Using version 2.7.1 

![image](https://user-images.githubusercontent.com/34923439/197050953-0e0639d1-d955-479d-89be-0be228b0cada.png)

**Comment by Sqrrl** [comment]
Hard to tell from the screenshot alone. Could you provide a reproduction repo?

**Comment by theskupi** [comment]
Hello, not sure if it's still relevant for @spencerfrost but maybe it will help someone else in the future. I encountered the same problem in my project and what helped me was to add postcss 8 as dev dependency in project's root:
`npm add -D postcss@8 `

More info [here](https://github.com/stylelint-scss/stylelint-config-standard-scss/issues/5) 🙂
