### ISSUE TITLE
Is there a particular reason to expose viteFinalFactory for users?

### ISSUE THREAD

**Issue by yannbf** [UX-and-I/storybook-design-token#136]
Hey! This addon sounds great and I love that it supports Vite!
I was wondering if it's really necessary to expose a setup step for Vite users, or if this addon could just provide a `viteFinal` export instead, as part of its preset. This way the users don't even need to know what to set up, things should just work automatically. It works similarly than webpackFinal, which this addon already does.

Here's an example of an addon that supports both Webpack and Vite:
https://github.com/storybookjs/addon-coverage/blob/main/src/preset.ts#L6

**Comment by Sqrrl** [comment]
Hey. Thanks for the tip. As far as I know, viteFinal wasn't yet supported within the presets when I was implementing the Vite support. But could be wrong on that. Works great now, so I added the preset and removed the extra configuration steps from the readme. Will release it with v2.8.0.

**Comment by yannbf** [comment]
Oh interesting. @IanVS Is there a possibility `viteFinal` is not supported in `storybook-builder-vite` but is now in `@storybook/builder-vite` ?

**Comment by IanVS** [comment]
AFAIK, the builder has always supported it, but it's possible that storybook presets did not.

**Comment by Sqrrl** [comment]
Thanks for the insight. Maybe I was just wrong. Closing this.
