### ISSUE TITLE
viteFinal blocks extra config merge

### ISSUE THREAD

**Issue by yarinsa** [UX-and-I/storybook-design-token#139]
Before adding this addon we had something like:
```
  async viteFinal(config: UserConfig, { configType }: { configType: string }) {
    return mergeConfig(config, viteConfig({ command: 'serve', mode: configType.toLowerCase() }));
  },
```
The motivation for this is that we have vite.config.ts (which includes all the complex stuff) and we have storybook/vite.config.ts which includes some overrides specific for storybook. 

My naive assumption that viteFinalFactory accepts config and do the same merge logic. But apparently it accepts "options" as the plugin options. 
My workaround was doing what viteFactoryFinal do. I didn't pass this option and did the following in my storybook/vite.config.ts
![Screen Shot 2022-11-17 at 11 09 04](https://user-images.githubusercontent.com/44482362/202403953-276f602f-b45b-49e4-8a53-2b8d032a6a34.png)

I am willing to help fixing this interface and contribute to the project

**Comment by yannbf** [comment]
This is related to this question: #136
Supposedly there could be no reason to even provide such a factory function, and just accept the addon configuration via the addons entry in main.js

**Comment by Sqrrl** [comment]
The usage of viteFinalFactory is obsolete with v2.8.0. You should be able to remove it from you config. Please let me know if that fixes your issue.

**Comment by yarinsa** [comment]
It did. Used your plugin directly in my vite.config.ts
