### ISSUE TITLE
Provide ability to disable or increase page size in TokenCards component

### ISSUE THREAD

**Issue by jgornick** [UX-and-I/storybook-design-token#143]
Currently the TokenCards component is [hard coded to paginate at 50 items](https://github.com/UX-and-I/storybook-design-token/blob/master/addon/src/components/TokenCards.tsx#L26).

We would like to disable pagination altogether, or at least provide a much larger page size.

Is this as simple as providing the `pageSize` as a prop on the component?

**Comment by jgornick** [comment]
FYI, totally willing to submit a PR, but just wanted to double check to make sure this hard coded value has a reason.

**Comment by Sqrrl** [comment]
A PR would be great. No real reason for the default.

**Comment by acherkashin** [comment]
@Sqrrl  @jgornick I've created a pull request for this feature #155

**Comment by acherkashin** [comment]
@jgornick Feature is merged and released in the new version
