### ISSUE TITLE
Animation Presenter Not Working

### ISSUE THREAD

**Issue by Jeremy-Walton** [UX-and-I/storybook-design-token#160]
The animation presenter doesn't seem to be working. It shows the token in the right category, but it does not animate it.

I copied from the example in the demo and it won't animate.

I am using `v2.9.0` with Storybook `Storybook 6.5.14 for Html`

My `main.js` looks like
```js
addons: [
  '@storybook/addon-links',
  '@storybook/addon-essentials',
  '@storybook/addon-interactions',
  '@storybook/preset-scss',
  { name: 'storybook-design-token', options: { preserveCSSVars: true } },
],
```

My token:
```
/**
  * @tokens Animation
  * @presenter Animation
  */
  --op-animation-flash: rotate 1.2s infinite cubic-bezier(0.55, 0, 0.1, 1);
```
![Screenshot 2023-03-08 at 12 00 42 PM](https://user-images.githubusercontent.com/5957102/223779392-4ca6705c-b587-4b30-a827-0849cde0389a.png)

**Comment by Sqrrl** [comment]
The addon tries to extract @keyframes declarations from your style sheets, which seems to fail in your case. Is the addon picking up the file including the keyframes? Where is the "rotate" animation defined?

**Comment by Jeremy-Walton** [comment]
Ah yeah I didn't have that defined. I pulled from the demo app in this repo but didn't copy the keyframes. The particular case I was trying doesn't show since I am animating the `right` attribute and the preview doesn't have a `position: absolute` set.
