### ISSUE TITLE
Issue starting storybook-design-token

### ISSUE THREAD

**Issue by Kavallier** [UX-and-I/storybook-design-token#169]
Following the documentation on your Readme.MD, I have run `npm add --save-dev storybook-design-token` and then adding the addon `'storybook-design-token'` to .storybook/main.js.

When I start storybook I get the following error:

`95% emitting StorybookDesignTokenPlugin/.../node_modules/storybook-design-token/dist/plugin.js:110
                    return [2 /*return*/, JSON.stringify({
                                               ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at /.../node_modules/storybook-design-token/dist/plugin.js:110:48
    at step (/.../node_modules/storybook-design-token/dist/plugin.js:33:23)
    at Object.next (/.../node_modules/storybook-design-token/dist/plugin.js:14:53)
    at fulfilled (/.../node_modules/storybook-design-token/dist/plugin.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

These are the add-ons we are currently using:
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-controls",
    "@storybook/addon-interactions",
    "@whitespace/storybook-addon-html",
    "@storybook/addon-a11y",
    "storybook-design-token"

**Comment by Sqrrl** [comment]
Seems like it fails because of the length of parsed token files. You could try to specify a custom glob to reduce the amount of files being parsed. https://github.com/UX-and-I/storybook-design-token#specify-a-custom-glob-for-your-token-files

Could you tell me, how many token files (css, scss, less, svg) he is picking up?

**Comment by Kavallier** [comment]
Thanks for replying.

I only have the one file with comments in it, but as far as the number of files it looks for, that could be a lot larger.

Where do I put the configuration on mainjis? I’m not really sure of how to configure the glob. I’d be more than happy to configure it to a single file as that is all we need.

On 16 Jun 2023, at 23:01, Philipp ***@***.***> wrote:

﻿

Seems like it fails because of the length of parsed token files. You could try to specify a custom glob to reduce the amount of files being parsed. https://github.com/UX-and-I/storybook-design-token#specify-a-custom-glob-for-your-token-files

Could you tell me, how many token files (css, scss, less, svg) he is picking up?

**Comment by Sqrrl** [comment]
Example via main.js: 

```js
module.exports = {
  addons: [
    {
      name: "storybook-design-token",
      options: {
        designTokenGlob: "**/*.token.{css,scss}",
      },
    },
  ],
}
```

This would only parse files ending on ".token.css" and ".token.scss".

Alternatively, you can set the environment variable before starting/building Storybook, e.g. via the package.json or a .env file.

`DESIGN_TOKEN_GLOB=**/*.token.{css,scss} npm run storybook`

**Comment by Kavallier** [comment]
Really helpful, thank you so much.
Back at work on Tuesday, will try then and let you know how it goes.

On 17 Jun 2023, at 00:20, Philipp ***@***.***> wrote:

﻿

Example via main.js:

module.exports = {
  addons: [
    {
      name: "storybook-design-token",
      options: {
        designTokenGlob: "**/*.token.{css,scss}",
      },
    },
  ],
}

This would only parse files ending on ".token.css" and ".token.scss".

Alternatively, you can set the environment variable before starting/building Storybook, e.g. via the package.json or a .env file.

DESIGN_TOKEN_GLOB=**/*.token.{css,scss} npm run storybook

**Comment by Kavallier** [comment]
That seemed to do the trick, really associate your assistance with this.

Thank you so much for helping out

On 17 Jun 2023, at 07:55, Darren Bonnici ***@***.***> wrote:

﻿
Really helpful, thank you so much.
Back at work on Tuesday, will try then and let you know how it goes.

On 17 Jun 2023, at 00:20, Philipp ***@***.***> wrote:

﻿

Example via main.js:

module.exports = {
  addons: [
    {
      name: "storybook-design-token",
      options: {
        designTokenGlob: "**/*.token.{css,scss}",
      },
    },
  ],
}

This would only parse files ending on ".token.css" and ".token.scss".

Alternatively, you can set the environment variable before starting/building Storybook, e.g. via the package.json or a .env file.

DESIGN_TOKEN_GLOB=**/*.token.{css,scss} npm run storybook

**Comment by Kavallier** [comment]
Limiting what files to discover via glob resolved this
