### ISSUE TITLE
Gradient presenter not displaying gradient

### ISSUE THREAD

**Issue by peterbroomfield** [UX-and-I/storybook-design-token#19]
[](url)
<img width="1419" alt="Screen Shot 2020-05-30 at 12 12 55 AM" src="https://user-images.githubusercontent.com/53009735/83319258-d8451480-a20a-11ea-8406-8ae6109ffb0c.png">

**Comment by Sqrrl** [comment]
Hey. Will look into this.

**Comment by Sqrrl** [comment]
Hey, fixed with v0.7.7 … I hope. ;)
