### ISSUE TITLE
Module not found error after install

### ISSUE THREAD

**Issue by davidrpoliti** [UX-and-I/storybook-design-token#2]
After getting storybook running locally, I install the addon and get this error

### Error
<img width="549" alt="Screenshot 2019-10-07 22 36 10" src="https://user-images.githubusercontent.com/4054043/66369892-0790d380-e953-11e9-9bc1-f184c81aa765.png">

### Storybook config
```
import { configure, addParameters } from '@storybook/react';


const path = require('path');
const scssReq = require.context('!!raw-loader!./_variables.scss', true, /.\.scss$/);
const scssTokenFiles = scssReq.keys().map(filename => ({ filename, content: scssReq(filename).default }));


addParameters({
 designToken: {
   files: {
     css: cssTokenFiles,
     scss: scssTokenFiles,
     //svgIcons: svgIconTokenFiles
   }
 }
});

// automatically import all files ending in *.stories.js
configure(require.context('../src/stories', true, /\.stories\.js$/), module);
```

**Comment by Sqrrl** [comment]
Hey. The part after `!!raw-loader!` should match the path of your token files. It should look like this, if you only want to parse the _variables.scss file:

`const scssReq = require.context('!!raw-loader!.', true, /_variables\.scss$/);`

Make sure that the path is relative to your config.js file location. Is your _variables.scss really located inside the .storybook directory?

**Comment by davidrpoliti** [comment]
@Sqrrl thanks, this got me rolling again. 
What’s the escape syntax to go into an adjacent folder or a few levels up?

**Comment by Sqrrl** [comment]
Assuming your file is located in an adjascent folder called „styles“:

require.context('!!raw-loader!../styles', true, /_variables\.scss$/);

**Comment by davidrpoliti** [comment]
Magic. That worked. Thank you!
