### ISSUE TITLE
Is there a way to only show the utilized Design Tokens in a given Story?

### ISSUE THREAD

**Issue by fglendrange** [UX-and-I/storybook-design-token#203]
Is there a way to filter the tokens displayed in each story? 

I am using plain CSS and have a separate file for eg. colors.css that contains all my colors as variables and the special design-token annotation. 
I reference the relevant variables in each component. E.g. in button.css there is a `color: var(--brand-primary);` 

Now I get a list of all color tokens in all my components, not just the ones in use in the specific component.

**Comment by Sqrrl** [comment]
Yes. You should be able to specify the parsed files via https://github.com/UX-and-I/storybook-design-token/tree/v3?tab=readme-ov-file#specify-a-custom-glob-for-your-token-files.

**Comment by fglendrange** [comment]
Thank you - That sounds promising! I am a bit uncertain as to how I am supposed to do this? Should I mark my component-based CSS classes in a distinct way and have the parser only look for those files? And it would thus exclude any design-tokens in the global files in each story. Or am I misunderstanding something here?

**Comment by Sqrrl** [comment]
Assuming you have separate files including your tokens (colors.css, spacings.css, …), I would define a blob pattern that only matches these token files. You could name all your token files *.tokens.css for example, and use a glob pattern like `**/*.tokens.{css,scss,less,svg}`. Or you could use the glob pattern to "whitelist" only specific file names (e.g. `**/{colors,spacings}.css`).

**Comment by fglendrange** [comment]
I apologize for my slow-ness here - I still am not sure I have understood this correctly. 

Given this "global" `Colors.tokens.css` file:
```
:root {
    /**
    * @tokens Colors
    * @presenter Color
    */
    --color-button-primary: #1ea7fd;
    --color-button-primary-hover: #1b7ec2;
    --color-button-primary-active: #116699;
    --color-button-primary-disabled: #a0dfff;
    --color-button-secondary: #e9ecef;
    --color-button-secondary-hover: #e2e6ea;
    --color-button-secondary-active: #d4d8db;
    --color-button-secondary-disabled: #f1f3f5;
}
```

And a `Button.css` file like this:
```
.storybook-button--primary {
  background-color: var(--color-button-primary);
}
.storybook-button--primary:hover {
  background-color: var(--color-button-primary-hover);
}
.storybook-button--primary:active {
  background-color: var(--color-button-primary-active);
}
.storybook-button--primary:disabled {
  background-color: var(--color-button-primary-disabled);
}
```

I would assume that the color tokens for `--color-button-secondary*` to not be shown in the tab in the button story as it is not utilized in this component? Am I mistaken?

<img width="1611" alt="Skjermbilde 2023-12-20 kl  14 12 19" src="https://github.com/UX-and-I/storybook-design-token/assets/74543116/cb509d69-9c57-4404-9f99-e559fe9b18ff">

**Comment by Sqrrl** [comment]
The Design Tokens tab in the addon panel isn't aware of which tokens the currently open component uses. It will always show all tokens. Currently there is no way to filter tokens by component usage.
