### ISSUE TITLE
Minor logic/render bug in version 0.7.4.

### ISSUE THREAD

**Issue by MihaelN** [UX-and-I/storybook-design-token#22]
Minor bug in version 0.7.4.

**Steps to reproduce:**
If there are no hardcoded values, after the last separator in the Design Token tab `"0"` is rendered. I am assuming it renders the length of 0 when no hardcoded values can be found.

I am referring to line 60 in node_modules `storybook-design-tokens/dist/component/Panel.js` 

----

https://github.com/UX-and-I/storybook-design-token/blob/fc491d95dad1b8c032db10509120d5d796627538/src/components/Panel.tsx#L80

**Comment by 11joselu** [comment]
I see that bug too.

My bad with my MR at #20

**Comment by Sqrrl** [comment]
Thank you both. Published as v0.7.5
