### ISSUE TITLE
Issue: Aliased/Inherited CSS Variables don't show up

### ISSUE THREAD

**Issue by sverrehagen** [UX-and-I/storybook-design-token#32]
When I do e.g.

```
--base-size: 16px;
--font-size-default: var(--base-size);
```

The latter don't show up in the tokens panel. However, it does show up if i do:

`--font-size-default: calc(1 * var(--base-size));`

Perhaps some issue with `var(...)` being the first part of the variable?

**Comment by Sqrrl** [comment]
Hey, it should show up in the `Aliases` column of the `--base-size` row. Are you expecting `--font-size-default` to show up in a separate row?

**Comment by sverrehagen** [comment]
```css
/**
 * @tokens Font Sizes
 * @presenter FontSize
 */
:root {
    --font-size-10: calc(0.625 * var(--font-size-16));
    --font-size-12: calc(0.75 * var(--font-size-16));
    --font-size-14: calc(0.875 * var(--font-size-16));
    --font-size-16: var(--root);
    --font-size-18: calc(1.125 * var(--font-size-16));
    --font-size-24: calc(1.5 * var(--font-size-16));
    --font-size-32: calc(2 * var(--font-size-16));
}
```

If I do this, `--font-size-16` does not show up under `Font Sizes`.

`--root` is defined in another file, and not really something I want to show up in the Design Token explorer, because it's not meant to be consumed directly anywhere.

**Comment by Sqrrl** [comment]
Got it. Could you try v0.8.1?

**Comment by f2-107** [comment]
Hi Philipp,

we have a similar issue but in the SCSS files. When we have a block like this:
```
/**  
  * @tokens Background Colors  
  * @presenter Color  
*/
 $background-dark-blue: $blue-02; 
$background-white: $white;
 $background-grey: $neutral-01; 
$background-sand: $sand-03;
 $background-sand-light: rgba($sand-03, 40%); 
$background-green: $green-04;
 $background-green-light: $green-01;
```
Then only `background-sand-light` shows up, but white. Maybe because it won't solve the `$sand-03` variable inside.

Is it a similar issue or should it be a new one?

**Comment by Sqrrl** [comment]
Closing this. Please re-open if the issue still exists.

**Comment by laddi-netapp** [comment]
I see that `alias` has been removed in later versions, was that on purpose?  Would like to use that if possible...
