### ISSUE TITLE
Support for Storybook: OpenWC

### ISSUE THREAD

**Issue by ARuzek** [UX-and-I/storybook-design-token#33]
Windows 10
Chrome 86
Storybook 5.3.10 : Framework Web Components
Build Framework via OpenWC

This add-on produced the following errors in browser: 
```
Uncaught ReferenceError: exports is not defined at public_api.js:5
Uncaught ReferenceError: require is not defined at preview.js:3
```

**Comment by Sqrrl** [comment]
Hey, I can reproduce the error with a clean OpenWC project. I don't think it is a general issue with web components, but with the OpenWC build setup.

The storybook addon is published as a CommonJS module, which I'm guessing is not supported by the OpenWC setup. I'm not sure how to work around this, as I have never used OpenWC. I will try to publish the addon as an ES6 module in the future. Maybe that will solve your issue.

**Comment by ARuzek** [comment]
Sounds good, thanks!
