### ISSUE TITLE
SCSS parser problem

### ISSUE THREAD

**Issue by aasen** [UX-and-I/storybook-design-token#39]
Hi!

I am trying to use this cool addon, and I'm following the setup _exactly_ as described for v1.0.0. I've checked the example 100 times.

The build goes without problems, but I get a problem in the browser:
```
Uncaught (in promise) CssSyntaxError: /scss/filename.scss:1:1: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
```

I'm on storybook 6.1.21, and setup is totally basic. I use @storybook/preset-scss addon for scss, but I don't think that is anything but normal. The webpackFinal setup in main.js looks like this:
```
  webpackFinal: async (config, { configType }) => {
    config.module.rules.push({
      test: /\.scss$/,
      loaders: ["style-loader", "css-loader", "sass-loader"],
    });
    return config;
  },
```

I then load the scss file like this in preview.js: `import "!style-loader!css-loader!sass-loader!../src/assets/scss/filename.scss";`

Is this a bug, or is it me doing something wrong?

**Comment by Sqrrl** [comment]
Hey. Just tried it myself with @storybook/preset-scss. Could not reproduce the issue, unfortunately. 

A few questions:
Does the error disappear when you remove the design token addon from the project?
Could you post your preview.js?
The custom webpack config doesn't seem to be required by the scss preset. Are you sure that it's necessary?

**Comment by aasen** [comment]
It works when I remove the addon from the project. But you are right, I don't need the special webpack-setup for scss-support. After a reinstall here, I see that I get lots of version changes for postcss modules. I'll try and retry adding the design token addon now.

Thanks for helping.

**Comment by aasen** [comment]
No, sadly it still fails with same error. I'll share some code:

preview.js
```
import { themes } from "@storybook/theming";
import "./css/storybook-overrides.css";
import "../src/ressurser/scss/atlantis.scss";

const tokenContext = require.context(
  "!!raw-loader!../src",
  true,
  /.\.(css|less|scss|svg)$/
);

const tokenFiles = tokenContext.keys().map(function (filename) {
  return { filename: filename, content: tokenContext(filename).default };
});

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  designToken: {
    files: tokenFiles,
  },
  docs: {
    theme: themes.oslo,
  },
  layout: "centered",
  options: {
    storySort: {
      method: "alphabetical",
      order: [
        "Designsymboler",
        ["Introduksjon"],
        "Ressurser",
        ["Introduksjon"],
        "Komponenter",
        ["Introduksjon"],
        "Moduler",
        ["Introduksjon"],
        "Maler",
        ["Introduksjon"],
      ],
    },
  },
};
```

main.js
```
module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-essentials",
    "@storybook/addon-links",
    "@storybook/preset-scss",
    "storybook-addon-designs",
    "storybook-design-token",
  ],
  refs: {
    "design-system": {
      title: "Storybook Design System",
      url: "https://oslo-components-vue.minside-dev.oslo.systems",
    },
  },
};
```

color.stories.mdx
```
import { DesignTokenDocBlock } from "storybook-design-token/dist/doc-blocks";
<DesignTokenDocBlock categoryName="Colors" viewType="table" />
```

In addition I've added comments in the scss colors, as in the example.

**Comment by Sqrrl** [comment]
Thanks. Might have a clue where it's coming from. Still not sure why I can't reproduce it.

Could you provide the stacktrace for the "You tried to parse SCSS ..." error?

**Comment by aasen** [comment]
I'm guessing its my fault...

```
Uncaught (in promise) CssSyntaxError: /ressurser/scss/filename.scss:2:4: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
    _construct css-syntax-error.js:20
    Wrapper css-syntax-error.js:18
    CssSyntaxError css-syntax-error.js:71
    error input.js:128
    unknownWord parser.js:561
    decl parser.js:233
    other parser.js:131
    parse parser.js:75
    parse parse.js:17
    LazyResult lazy-result.js:64
    process processor.js:142
    process processor.js:121
    getNodes postcss.parser.js:189
    getNodes postcss.parser.js:186
    step postcss.parser.js:44
    verb postcss.parser.js:25
    __awaiter postcss.parser.js:19
    __awaiter postcss.parser.js:15
    getNodes postcss.parser.js:155
    parseCssFiles postcss.parser.js:62
    step postcss.parser.js:44
    verb postcss.parser.js:25
    __awaiter postcss.parser.js:19
    __awaiter postcss.parser.js:15
    parseCssFiles postcss.parser.js:58
    useTokenTabs useTokenTabs.js:55
    React 6
    unstable_runWithPriority scheduler.development.js:653
    React 3
    workLoop scheduler.development.js:597
    flushWork scheduler.development.js:552
    performWorkUntilDeadline scheduler.development.js:164
    js scheduler.development.js:187
    js scheduler.development.js:857

```

**Comment by Sqrrl** [comment]
Could you try out v1.01? Might solve your issue.

**Comment by aasen** [comment]
It works!

There is a design bug under approx 1000px page width on table, but except that it works beautifully.

My colors was initially set with sass variables, and that don't work here, so I'll have to set them differently for this.

Great work, thanks a lot for taking time to help me out.
