### ISSUE TITLE
Border radius presenter sizing when 

### ISSUE THREAD

**Issue by tiaanduplessis** [UX-and-I/storybook-design-token#41]
Hi 👋🏻 

Thanks for maintaining this package. I'm currently experiencing an issue when using a large value with the border-radius presenter. The final output is quite large.

 E.g. `999px` results in:

<img width="1208" alt="Screenshot 2021-04-21 at 17 23 24" src="https://user-images.githubusercontent.com/18066992/115579277-4af92b80-a2c6-11eb-9b15-04ea9ba70dc6.png">

I believe this is due to the way the `min-height` and `min-width` is currently being calculated for the component -> https://github.com/UX-and-I/storybook-design-token/blob/master/addon/src/components/presenter/BorderRadiusPresenter.tsx#L20

**Comment by Sqrrl** [comment]
Right … Didn‘t consider large values here. I‘ll think about a better way to present these values. Thanks for the feedback.
