### ISSUE TITLE
Disable the add-on tab

### ISSUE THREAD

**Issue by kiwi-admin** [UX-and-I/storybook-design-token#44]
Is it possible to disable the "Design Tokens" Addon tab and still use Design Token Doc Blocks?

For example Essential's addons use the following [disabling option](https://storybook.js.org/docs/react/essentials/introduction#disabling-addons) syntax.

I've seen the [active](https://github.com/UX-and-I/storybook-design-token/blob/60ff5c31aa52bcbc02158ad7afdf6d07195d6169/addon/src/register.tsx#L16), but don't know how to officially use it.

I've tried to pass the `tabs` as an empty array. But it did not worked out. If any of these options are allowed having them documented would be helpful.

**Comment by lmestel** [comment]
You can just remove the addon from the `addons` array in main.js. The DesignTokenDocBlock still works.

**Comment by Sqrrl** [comment]
> You can just remove the addon from the `addons` array in main.js. The DesignTokenDocBlock still works.

This should do the trick.
