### ISSUE TITLE
Storybook modules as peer dependencies?

### ISSUE THREAD

**Issue by edoardocavazza** [UX-and-I/storybook-design-token#53]
Hello! Thank you for this addon, it is very very useful. I noticed that core Storybook modules like `@storybook/addons`, `@storybook/components` and `@storybook/theming` are treated as addon's dependencies. Shouldn't they be defined as peer dependencies instead? Any downside?

**Comment by Sqrrl** [comment]
Hey. At least I couldn't find a framework package that doesn't include these dependencies. I'll check if they can be removed with the next release.

Only downside would be that you'd have to install these packages yourself if the peer dependency versions don't match, right?
