### ISSUE TITLE
Bug: Encountered two children with the same key

### ISSUE THREAD

**Issue by dexster** [UX-and-I/storybook-design-token#55]
This error occurs when using design tokens in an Angular project. 

![Screenshot 2021-08-18 at 12 10 14](https://user-images.githubusercontent.com/6392334/129880664-7612d974-bdfb-4fed-8778-56c1cae9338f.png)

This error occurs on a clean install of Storybook 6.3.7 and also 6.4-alpha.30 for Angular. The error appears for each CSS variable in the stylesheet.

To replicate:

1. `ng new testtoken`
2. You can choose CSS or SCSS when prompted. They both have the issue.
3. `cd testtoken`
4. `npx sb init`
5. `npm install storybook-design-token --save`

Add the requited token configuration to main.js and preview,js,

Add token comments to styles.scss
 
```
:root {
 
  /**
  * @tokens Colors
  * @presenter Color
  */

  --b100: hsl(240, 100%, 90%); /* Token Description Example */
}
```

ng serve

Additional info:

ng version: 12.0.2 or 12.2.1 (issue occurs on both)

**Comment by resource11** [comment]
Same issue here.

I'm using 
```"react": "16.13.1",
"typescript": "4.2.3",
"postcss": "8.3.6",
"@storybook/react": "6.3.7", (etc)
"storybook-design-token": "1.0.2",
```

**Comment by Sqrrl** [comment]
The addon doesn't handle duplicate token definitions at the moment. I'm assuming you defined the token (--PRIMARY-COLOR) multiple times in the stylesheets you import in your preview.js.

**Comment by dexster** [comment]
No. I tested with a clean project which has no style imports anywhere, only the token config pointing to one stylesheet that has this in it
```
/**
* @tokens Colors
* @presenter Color
*/
:root {
  --PRIMARY-COLOR: #0033aa;
}
 
```

**Comment by Sqrrl** [comment]
Thanks for the update. I will try to reproduce this.

**Comment by 2rule** [comment]
Hello there, has there been any updates on this? I just came across this addon and I think it's fantastic! @Sqrrl 🎉

**Comment by Sqrrl** [comment]
Pretty busy right now. But it‘s on top of my list.

**Comment by Sqrrl** [comment]
The issue is caused by files being accidentally parsed twice.

Could you check if v1.2.2 fixes it for you?

**Comment by resource11** [comment]
YES! This works for me. No more triplicate token definitions in React/TS Storybook instance. Thank you, @Sqrrl!
