### ISSUE TITLE
Allow to define custom categories on SVG icons

### ISSUE THREAD

**Issue by yakky** [UX-and-I/storybook-design-token#56]
Currently there is no way to define categories for SVG icons, like it's available for the other tokens

In case a design system contains lots of icons the resulting page is confusing and not friendly.

By using data attribute on each SVG we can provide a category name, group icons according to this category and use the category name in DesignTokenDocBlock to display the corresponding tokens.

**Comment by Sqrrl** [comment]
Sounds reasonable and should be low effort. I'll try to fit it in the next version.
