### ISSUE TITLE
Issues with Storybook v.6.4.0 beta?

### ISSUE THREAD

**Issue by edoardocavazza** [UX-and-I/storybook-design-token#59]
Hello! I am trying to update my storybook to the v6.4.0 beta version, but it breaks when using
```
<DesignTokenDocBlock categoryName="Colors" viewType="card" />
```
at this lines:
```
var context = react_1.useContext(blocks_1.DocsContext);
var tabs = useTokenTabs_1.useTokenTabs(context.parameters.designToken).tabs;
```
because it seems that `context.parameters` is not defined anymore. It is a known bug? Is there any workaround?

Thanks!

**Comment by Sqrrl** [comment]
Hey. Thank you for reporting. I would like to wait for 6.4 to be out of beta before adapting to the context changes that come with it.

I will keep this issue open.

**Comment by Sqrrl** [comment]
Thank you for your PR. Much appreciated. Release with v1.2.3.

**Comment by edoardocavazza** [comment]
Thank you!
