### ISSUE TITLE
Preview not working for colors defined with `!default`

### ISSUE THREAD

**Issue by gabriela-it** [UX-and-I/storybook-design-token#6]
Hi there,
Thank you for sharing this great work!

Here is a shot of the problem:
![2020-01-20 - SCSS Variables with Default](https://user-images.githubusercontent.com/9743044/72746094-2be28a00-3ba9-11ea-94d7-62eada5e3492.png)

Thanks!

**Comment by Sqrrl** [comment]
Thanks. Need to filter out ! statements, it seems. I‘ll fix that with the next release.

**Comment by Sqrrl** [comment]
Fixed with v0.5.1
