### ISSUE TITLE
Not IE11 compatible

### ISSUE THREAD

**Issue by mario-dicarlo** [UX-and-I/storybook-design-token#8]
Can this be made IE11 compatible?

E.g. can packages like @illinois/react-use-local-storage be replaced with an alternative as it uses arrow functions?

**Comment by Sqrrl** [comment]
Looking into this. Thanks for reporting.

**Comment by Sqrrl** [comment]
Hey. So the issue with the local storage lib can be resolved easily. Unfortunately there is at least one other library (comment-parser) that is not IE11 compatible and isn't replaced as easily. I'll try to get this working at some point, but cannot commit to it right now. Sorry.

**Comment by Smolations** [comment]
@Sqrrl Is it possible to transpile that dependency down to es5 by using a custom webpack config in storybook? Basically, is there any other workaround besides a change in this project?

**Comment by Sqrrl** [comment]
Thought about that, too. I don't think it is possible using TypeScript, but you could add Babel or the like to the build setup to transpile dependencies. Not sure if that's a good idea, though.

**Comment by Smolations** [comment]
@Sqrrl Just giving a little nudge on this issue. 

Additionally, I recently came across [a similar issue](https://github.com/pocka/storybook-addon-designs/issues/28) in another 3rd party storybook addon. That maintainer was convinced to fix the issue given the direction [in the storybook docs](https://storybook.js.org/docs/addons/writing-addons/#package-maintenance):

> Your packaged Storybook addon needs to be written in ES5. If you are using ES6, then you need to transpile it.

While _this_ particular issue is related to a dep in your library and not the library itself, I think the takeaway is that the accessible npm package needs to be _completely_ es5 compatible. 

Anywho, really looking forward to this issue getting resolved when you get around to it!  😋

**Comment by Sqrrl** [comment]
The comment parser is used for the comment blocks in stylesheets. Examples are here: https://github.com/UX-and-I/storybook-design-token#usage
This is done during runtime.

I'm pretty busy right now, but will try to add an es5 bundle of the addon as soon as possible.

**Comment by Sqrrl** [comment]
Hey, I just published a tagged release to NPM which should work in IE11. Would be great if you could install `storybook-design-token@ie11` and check if it is working for you.

It works on my machine (🙄), but would be great to have this verified by you guys, so I can make a proper release.

**Comment by Smolations** [comment]
@Sqrrl Yea no problem! I'll check it out today, thanks! 👏

**Comment by Smolations** [comment]
@Sqrrl Oooooohhh yeeeaaaaaaa! We have IE11 support! Loads up just fine for me, pretty much immediately. I say ship it! 👍 

Will this be the new default bundle?

Also, not sure if this is related, but in the token knobs tab (redesign looks _fantastic_ btw!) I am seeing an empty section the origin from which I'm unsure of:

<img width="541" alt="Screen Shot 2020-05-15 at 11 30 09 AM" src="https://user-images.githubusercontent.com/952681/82079774-a8413180-96a0-11ea-8145-81fdd91b4d1c.png">

**Comment by Sqrrl** [comment]
Hey, thanks for testing. Released as 0.7.3.

The empty panel is for hard coded values in your css that match existing custom properties. I should hide this if it is empty. Closing this issue nonetheless.
