### ISSUE TITLE
Console error on Mozilla Firefox

### ISSUE THREAD

**Issue by exZerry** [UX-and-I/storybook-design-token#81]
[storybook-design-token](https://github.com/UX-and-I/storybook-design-token)/[addon](https://github.com/UX-and-I/storybook-design-token/tree/master/addon)/[src](https://github.com/UX-and-I/storybook-design-token/tree/master/addon/src)/[components](https://github.com/UX-and-I/storybook-design-token/tree/master/addon/src/components)/TokenValue.tsx

Line 53

Causes console error on Mozilla Firefox due to document.documentElement being null

**Comment by exZerry** [comment]
https://github.com/UX-and-I/storybook-design-token/pull/82/

**Comment by Sqrrl** [comment]
Merged and published (v2.0.1). Thank you very much.
