### ISSUE TITLE
design-tokens.source.json loaded using absolute URL

### ISSUE THREAD

**Issue by squarefeet** [UX-and-I/storybook-design-token#91]
Hello,

Thank you for this addon, it's been super-useful. I've got it all nicely integrated and working well, apart from when I deploy to my host. I've had a look through the documentation and all issues, but haven't come across anything related. 

After building Storybook, I deploy to my host, and the location of it isn't at the root, i.e. `https://my-host.com/sub-path/storybook/index.html`. This add-on attempts to load `design-tokens.source.json` from `https://my-host.com/design-tokens.source.json`, as opposed to this file's location relative to the `index.html` file.

It appears [this is hardcoded in `useTokenTabs`](https://github.com/UX-and-I/storybook-design-token/blob/57de7c0b01a0033ef3abc4d5593e7c3deac2a4dc/addon/src/hooks/useTokenTabs.ts#L51), and I was wondering if this was intentional and has a purpose I'm just not seeing, or could be made relative?

Altering this path to be `./design-tokens.source.json` appears to work fine for both local development and production deployments in my case.

Thanks!

PS. Happy to open a PR for this if you'd like.

**Comment by Sqrrl** [comment]
I think that might be an oversight by me. A PR would be great. Thanks for reporting.
