### ISSUE TITLE
Feature Request: Search for tokens

### ISSUE THREAD

**Issue by acherkashin** [UX-and-I/storybook-design-token#95]
Hi! 
Thank you for your awesome addon, really like it 👍. 

I think it is really important to be able to search tokens. For example, [material-ui](https://mui.com/material-ui/material-icons/) provides an ability to search icons in the documentation.

![image](https://user-images.githubusercontent.com/9947582/164157756-68d0b695-83ec-4c3b-bd4b-e24adc3088b9.png)

I started working on it and will create a pull request in a while if you don't mind. It is not final result, I just started, but it will work like this

![addon-search](https://user-images.githubusercontent.com/9947582/164157935-2e46bae3-d59b-4675-8be7-fac10644de24.gif)

Besides that, we need an ability to configure search visibility in case somebody wants to hide it.

**Comment by Sqrrl** [comment]
Really useful. Thank you very much. Released with v.2.3.0.

**Comment by acherkashin** [comment]
@Sqrrl Thank you for so quick response and merging it!
